### ISSUE TITLE
PyQt4.QAxContainer 모듈

### ISSUE THREAD

**Issue by zipu** [sculove/QWebview-plus#1]
안녕하세요^^ 

실행 시켜보니 PyQt4.QAxContainer 모듈이 없다고 에러가 나길래

conda로 pyqt4재설치도 해보고 윈도우 binary 설치도 해봤는데 같은 현상이 나타납니다.

python 3.5에서는 pyqt모듈이 아직 제대로 지원이 안되는것 같고, python 3.4에서는 잘 동작하네요.

참고하시기 바랍니다^^;

**Comment by sculove** [comment]
제가 개발하는 환경은 anaconda2.4.0 입니다. (python 3.5기반)입니다.
 anaconda2.4.1 에서는 저도 해당 모듈이 없다고 에러가 났었습니다.
anaconda 의 문제로 보입니다.
참고로, 32bit로 받아야 오픈 API를 사용할 수 있습니다.
감사합니다.
