### ISSUE TITLE
sendOrder 파라미터 개수 문제

### ISSUE THREAD

**Issue by mckim8686** [sculove/QWebview-plus#2]
안녕하세요~
공유해주신 python모듈로 트레이딩 프로그램 개발중입니다^^

프로그램 작성중에 주문이 안되는 문제가 있어서 살펴봤는데, 
dynamicCall함수 파라미터에 문제가 있어서 주문이 안되는 문제가 있어서 이슈 남겨드립니다.
http://doc.qt.io/qt-4.8/qaxbase.html#dynamicCall

저는 아래와 같이 수정했습니다~

``` python
def sendOrder(self, rQName, screenNo, accNo, orderType, code, qty, price, hogaGb, orgOrderNo ):
  variables = [rQName, screenNo, accNo, orderType, code, qty, price, hogaGb, orgOrderNo]
  return self.ocx.dynamicCall("SendOrder(QString, QString, QString, int, QString, int, int, QString, QString)", variables)
 #return self.ocx.dynamicCall("SendOrder(QString, QString, QString, int, QString, int, int, QString, QString)", rQName, screenNo, accNo, orderType, code, qty, price, hogaGb, orgOrderNo)
```

아래는 제가 사용중인 anaconda 버전입니다.
Python 3.5.0 |Anaconda 2.4.0 (32-bit)| (default, Oct 25 2015, 20:37:05) [MSC v.1900 32 bit (Intel)] on win32

혹시 저한테만 발생하는 문제라면 그냥 닫아주시기 바립니다^^

**Comment by sculove** [comment]
@mckim8686 오~ 감사합니다. 만드시는 프로젝트 저도 봐봤는데 도움이 많이 되네요.
이런건 Pull Request 주셔도 되요 ㅋ
