### ISSUE TITLE
크로니미움 변환 하기

### ISSUE THREAD

**Issue by sculove** [sculove/QWebview-plus#7]

**Comment by zipu** [comment]
pull request 날렸습니다.. 

근데 JavascriptConsoleMessage() 가 제대로 동작 안합니다. 
warning이랑 Error message만 출력을 하는데요..
qt document를 보니 qt5.6부터 logging category를 사용한다는데 어떻게 사용해야 하는지 잘 모르겠네요..
"[Since Qt 5.6, the default implementation logs the messages in a js logging category](http://doc.qt.io/qt-5/qwebenginepage.html#javaScriptConsoleMessage)"
qt5.6 아래 버전에서는 확인 안해봤구요..

**Comment by sculove** [comment]
@zipu #9 머지했습니다.
저도 확인해 볼께요. 다시 한번 감사합니다.

**Comment by zipu** [comment]
index.html에서 Promise 리턴하는 method로 생성하는 부분을
qwebchannel.js 내의 addMethods 함수를 아래처럼 수정하는 것도 가능하네요.
method name을 파싱하지 않아도 되고, kiwoom object내에 중복되는 method가 생기지 않는다는 장점이 있을거 같습니다.

```
    function addMethod(methodData)
    {
        var methodName = methodData[0];
        var methodIdx = methodData[1];
        object[methodName] = function() {
            var args = [];
            var callback;
            for (var i = 0; i < arguments.length; ++i) {
                if (typeof arguments[i] === "function")
                    callback = arguments[i];
                else
                    args.push(arguments[i]);
            }

            return new Promise(function(resolve){
                webChannel.exec({
                    "type": QWebChannelMessageTypes.invokeMethod,
                    "object": object.__id__,
                    "method": methodIdx,
                    "args": args
                }, function(response) {
                    if (response !== undefined) {
                        var result = object.unwrapQObject(response);
                        resolve(result);
                    }
               });
            });
        }
    }
```

**Comment by sculove** [comment]
@zipu qwebchannel.js를 바꾸는 것도 좋은 방법이네요.
하지만, 외부 라이브러리를 직접 고치는게 향후에 유지보수하기 힘들것 같아서요.

지금은 kiwoom object의 메소드를 원래 이름으로 재정의하는 것을 생각하고 있어요. 그동안 시간이 없어서 못했는데, 이번 주말에 할수 있을것 같네요. 머지되면 다시 피드백 주시면 좋겠어요. 항상 감사합니다.

**Comment by sculove** [comment]
@zipu 헉 크롬 50으로 업그레이드 된 이후로, Object.observe가 삭제되서 리모트 디버깅이 안되네요. ㅠㅠ

**Comment by sculove** [comment]
이벤트가 발생하는 시점과, commGetData 를 얻는 시점이 모두 비동기로 동작하여,
commGetData가 실제 실행되는 시점에는 데이터가 이미 없어진 상태임.
이로 인해 이벤트가 발생하는 시점에서 정확한 데이터를 얻지 못함 ㅠㅠ

**Comment by sculove** [comment]
크로니움기반에서 python 에서 크로니움 기반을 동기로 바꾸는 방법을 찾거나, Webkit2로 롤백해야할 상황

**Comment by sculove** [comment]
WebChannel은 전부 비동기. 동기를 사용할수 없음.
http://stackoverflow.com/questions/33536814/is-there-any-way-to-use-synchronous-function-call-through-qt-webchannel

현재 QWebview-plus 컨셉에 맞지 않음
`적용불가`

**Comment by zipu** [comment]
롤백 하신건 알고 있었는데 이런 이유가 있었는지는 몰랐네요. 저는 파이썬에서 이벤트 처리를 다 하고나서 javascript로 넘기는 방법을 사용하고 있어서 이런 문제가 있는지 전혀 몰랐네요.확실히 qwebview-plus 컨셉에는 맞지 않겠네요. 

키움에서 해외선물옵션용 API를 배포한 후로 새로 repository를 만들어서 개발하고 있다보니, 방문이 뜸했습니다. 덕분에 정말 큰 도움이 되었습니다. 혼자 시작했으면 까마득한 일들을 하고 있네요.
다시한번 감사합니다. 좋은 결과 있으시길 바랍니다.

**Comment by sculove** [comment]
@zipu 저도 요즘 바뻐서 ㅋㅋ 못하고 있답니다. 덕분에 저도 계속 진행할수 있네요 좋은하루되세요
