### ISSUE TITLE
브라우저 실행파일로 배포

### ISSUE THREAD

**Issue by sculove** [sculove/QWebview-plus#8]

**Comment by sculove** [comment]
https://pypi.python.org/pypi/py2exe/0.9.2.0

**Comment by llIllIllllIIIlllllll** [comment]
죄송한데 다운받은거 어떻게 사용해야하나요 며칠째 검색 다운 삭제 를 반복하고있어요..처음 파이선접해봅니다.ㅠㅠ

**Comment by sculove** [comment]
@vivlabss 아~ ㅋㅋ 어디서부터 도와드려야할지 ㅋㅋ

**Comment by sculove** [comment]
참조 http://sh1n2.tistory.com/123#recentTrackback

**Comment by sculove** [comment]
cx_freeze 환경 파일 작업 완료
